version: '3'

services: 

    nginx:
        image: nginx:alpine
        ports: 
            - 80:80
            - 443:443
        volumes: 
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: unless-stopped

    biedaflix_server:
        image: grottgera15/biedaflix-server:latest
        volumes: 
            - ./downloads:/usr/app/downloads
            - ./files:/usr/app/files
            - /usr/app/
        depends_on: 
            - qbittorent_vpn
            - database
        expose: 
            - 8081
        restart: unless-stopped

    qbittorent_vpn:
        container_name: qbittorent-vpn
        image: markusmcnugen/qbittorrentvpn
        cap_add:
            - net_admin
        devices:
            - /dev/net/tun
        environment:
            - VPN_ENABLED=yes
            - LAN_NETWORK=172.18.0.0/16
            - WEBUI_PORT_ENV=8080
            - INCOMING_PORT_ENV=8999
            - PUID=1000
            - PGID=1000
        ports:
            - 8080:8080
            - 8999:8999
            - 8999:8999/udp
        volumes: 
            - ./config:/config
            - ./downloads:/downloads
        restart: unless-stopped
    
    database:
        image : mongo
        environment:
            - MONGO_INITDB_DATABASE=biedaflix
        volumes:
            - ./mongodb-data:/data/db
        ports:
            - 27017:27017